### PR TITLE
Jakarta package change

### PR DESCRIPTION
**Pull request by gsmet**
@gunnarmorling @starksm64 I prepared this first PR to start the discussion.

One thing that will need more discussion is: which namespace should we use for our XSD? It used to be a JCP namespace and it doesn't really make sense.

Also, we have the old XSD in the artifact and... they contain `javax` and reference to the JCP, so do we have to drop them (I have no idea of the consequences of dropping them for the time being).

### CODE REVIEW

**Comment by gunnarmorling** [comment]
LGTM, @gsmet! I suppose you did a grep for "javax" to spot any remaining occurences?

In regards to XML namespaces, the jury is still out, see https://github.com/jakartaee/jakarta.ee/issues/592.

> Also, we have the old XSD in the artifact...

I think it's fine to just keep the current XSD in the API artifact. It's mostly there for documentory purposes anyways, so it was questionable that older versions where in there in the first place. HV has all of them locally.

**Comment by gsmet** [comment]
> I think it's fine to just keep the current XSD in the API artifact.

OK. I thought they wanted to get rid of all the references to `javax` and so on. I don't mind keeping them, just wanted to mention it.

**Comment by starksm64** [comment]
We probably should have a validation-configuration-3.0.xsd and validation-mapping-3.0.xsd even though we don't know what the namespace is, but that can wait for another PR when the namespace is defined.

**Comment by gsmet** [comment]
Yeah, I totally agree we need them. Not having the namespace was what prevented me to do it but I can create them and adjust later.

**Comment by starksm64** [comment]
@gsmet just do add the 3.0 schemas assuming a namespace of https://xmlns.jakarta.ee/xml/ns/jakartaee and I'll put out a milestone release to satisfy the current next step forward. We can fix it in the first RC once it is finalized.

**Comment by gsmet** [comment]
We have 2 different namespaces: `validation/mapping` and `validation/configuration`.

Should I go with: `https://xmlns.jakarta.ee/xml/ns/jakartaee/validation/mapping` or `https://xmlns.jakarta.ee/xml/ns/validation/mapping` without the `jakartaee`?

The old namespace used to be `http://xmlns.jcp.org/xml/ns/validation/configuration` so more like the second one.

I don't care either way.

**Comment by gsmet** [comment]
I pushed a change with `https://xmlns.jakarta.ee/xml/ns/validation/mapping` in both PRs.

Just tell me if I need to adjust it, I will.

**Comment by starksm64** [comment]
That namespace is fine for now, if it impacts the implicit usage of the namespace as a URL to obtain the schema from we can change that next release. Thanks.

**Comment by gunnarmorling** [comment]
> I don't mind keeping them, just wanted to mention it.

Sorry, it seems we miss understood. I meant to say I wouldn't mind having _only_ the 3.0 XSDs. But as per @starksm64 it seems fine to keep the other ones, too, so there seems to be no problem to begin with.

**Pull request merged**
